### ISSUE TITLE
Calling a function of another WickObject that throws an exception doesn't traceback correctly

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick-editor#255]

**Comment by zrispo** [comment]
1. create symbol named `foo` with a function `bar` that throws an error
2. call `foo` from another wickobject called `baz`
3. the correct error will be shown in the scripting IDE, but it highlights and shows the code of `baz`

**Comment by zrispo** [comment]
see `traceback-problem.html`

**Comment by zrispo** [comment]
Fixed with new script loading system
