### ISSUE TITLE
Adding variables outside of event funtions puts them in global scope

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick-editor#563]

**Comment by zrispo** [comment]
Some info:

When an object first appears on screen, the entire script is `eval`ed. Apparently any variables created in the eval get added to the global scope (inside `window`). So I guess we could wrap the `eval`ed code in some curly braces/a dummy function and that would fix this problem.

**Comment by zrispo** [comment]
We ain't using `eval()` anymore woo hoo so this is fixed
