### ISSUE TITLE
Feature request: Google Fonts

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick-editor#667]
The font selections are a bit limited, so [Google Fonts](https://developers.google.com/fonts/) support would be an awesome way to allow more creative designs. Considering this is an Alpha, it could be as simple as:
1. Find your desired font on Google's site
2. Type a font name and variant (e.g. 100, Thin, Bold, etc.) into Wick inspector fields
3. Using CSS, Wick pulls the font from the Google server if it exists

**Comment by zrispo** [comment]
Will be looking in to this soon

One problem I see is that google fonts only work if you're connected to the internet (this would be bad for downloaded projects, also if there's ever a wick desktop version you'd have to be connected to wifi to use all the fonts)

Buuut if i can figure out how to bundle fonts into projects, everything's fine! So we'll see

**Comment by zrispo** [comment]
So I recently got google fonts loading in Wick - it's a bit buggy, but it's really great to have over 800 fonts!!!!

Check out the `google-fonts` branch, as soon as this is working better I'll add it to the main version.

**Comment by Luxapodular** [comment]
Added in 0.13.2
