### ISSUE TITLE
Grabbing brush strokes with the Path Cursor is cumbersome

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick-editor#696]
When you mouse over a path, the nodes appear. The path cursor goes into edit mode if you click on the path; however, nodes block the path from being clicked. This makes it frustrating to edit brush strokes because they're relatively thin and rich in nodes.
![27bbb0fa-dbee-4af7-812c-e74c8954cbb8](https://user-images.githubusercontent.com/30781325/31058254-ca0c28d0-a6be-11e7-9845-c038e6ac5940.gif)

**Comment by zrispo** [comment]
I'm hoping that once we have the new brush in that this won't be as big of an issue, but I can't be sure. 

There's always the option of making the handles smaller though like in Illustrator:

http://pad1.whstatic.com/images/thumb/b/bb/Create-Text-on-a-Path-in-Adobe-Illustrator-Step-1-Version-3.jpg/aid732706-v4-728px-Create-Text-on-a-Path-in-Adobe-Illustrator-Step-1-Version-3.jpg

**Comment by kryptot7** [comment]
Hmm...I think it only starts acting up if you delete a node from a path (like I did above). I'm trying the path cursor on some ordinary strokes and it works fine.

> I'm hoping that once we have the new brush in that this won't be as big of an issue, but I can't be sure.
Does that mean the new brush will make more optimized strokes, i.e. with fewer nodes?

**Comment by zrispo** [comment]
The new brush is here! (in the prerelease: http://zrispo.co/wick-prerelease/editor.html)

There's also a few changes to the path cursor, so it might be easier to select things in general now.

**Comment by kryptot7** [comment]
Selecting things with the path cursor is much better as of 0.09pre. However, the margin for pulling at the edge of the stroke is generous, so it's easy to accidentally distort a stroke when you intend to select it and edit the nodes. In some cases you may have to zoom in.
A hotkey could help. Hold Shift as you're clicking an object with the path cursor, and you'll always select it and reveal the nodes without distorting it - even if you click the edge.

**Comment by zrispo** [comment]
Fixed in .13 with the new vector cursor
