### ISSUE TITLE
Input Events Do not fire on frames

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick-editor#737]
Check out this forum thread. 
http://forum.wickeditor.com/t/events-associated-with-frame-do-not-work/166/4

Here's an image from the thread showing what they tried. 
![image](https://user-images.githubusercontent.com/8699557/33613080-a5185682-d9a1-11e7-8e63-87b5455fd8e0.png)

**Comment by zrispo** [comment]
Fixxed in prerelease
