### ISSUE TITLE
The Fill Tool is Completely Broken. >:(

### ISSUE THREAD

**Issue by SomeWeirdo** [zrispo/wick-editor#740]
Whenever I click on the fill tool icon it messes up my drawings by undoing/redoing stuff I did before, and even when I ignore that, when I go click the space I want filled. It literally does nothing.

**Comment by zrispo** [comment]
Yup, current fill bucket is pretty borked, I've been working on a new one that _should_ work pretty well, but it's not quite ready yet.

You can test out the new fill bucket (and the other new stuff) in the prerelease editor: http://zrispo.co/wick12pre/

**Comment by SomeWeirdo** [comment]
Sweet, I'll be looking forward to the fix
