### ISSUE TITLE
Not really an issue. But why isn't there an eraser option?

### ISSUE THREAD

**Issue by SomeWeirdo** [zrispo/wick-editor#741]
I don't think I'm missing it. There **needs** to be an eraser.

**Comment by zrispo** [comment]
Fear not! A brand new eraser is coming in the next update -

![eraser](https://user-images.githubusercontent.com/4970417/34428975-41eb2206-ec20-11e7-9fe0-8504b6b3fcb0.gif)

Development is a little slow cause of the holidays, but we're trying to get the next update out pretty soon~

**Comment by SomeWeirdo** [comment]
Sick! That would be extremely useful! Honestly I find this to be better than photoshop.

Could we perhaps get a native desktop version? Sort of like what Discord and Skype does?

**Comment by Luxapodular** [comment]
@SomeWeirdo We're looking to eventually put out a desktop version of Wick. Not sure when but we're looking into it :)
