### ISSUE TITLE
Prerelease bug hunt

### ISSUE THREAD

**Issue by joshrispoli** [zrispo/wick-editor#742]
Hey everyone, here are a few bugs I found while playing with the prerelease version of Wick.

![screen shot 2018-01-05 at 1 08 53 am](https://user-images.githubusercontent.com/2821859/34597599-bbbc65fa-f1b5-11e7-906c-fe0137d79a1b.png)
Some strange behavior happens when you zoom and right-click.

![screen shot 2018-01-05 at 1 30 19 am](https://user-images.githubusercontent.com/2821859/34597978-186e2444-f1b8-11e7-8a08-b61f9dbe0c01.png)
Playing with the diagonal transform of one of these blue rectangles made it disappear.  The line thickness was also scaling with the transformation (though it would resize correctly later).

**Comment by zrispo** [comment]
Fixed all these in 0.12
