### ISSUE TITLE
When selecting paths, Inspector "Stroke Color" label is cut off

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick-editor#767]
![image](https://user-images.githubusercontent.com/30781325/36343832-0a0dc00a-13df-11e8-81c8-6473161f1b5d.png)

**Comment by zrispo** [comment]
the Inspector got an update in .14, looks much better now!:

![screen shot 2018-02-19 at 11 29 04 am](https://user-images.githubusercontent.com/4970417/36387873-257d2968-1568-11e8-9678-74c83758ba86.png)
