### ISSUE TITLE
Rectangle tool's adjustment option has no clear function

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick-editor#769]
![image](https://user-images.githubusercontent.com/30781325/36345168-e1068722-13f3-11e8-8d01-1675845711cd.png)
This UI element appears in the Tools panel when I'm using the Rectangle tool, but clicking or dragging on it doesn't seem to do anything

**Comment by Luxapodular** [comment]
We've got a UI update coming in 0.14 for this!

**Comment by zrispo** [comment]
Yup this element controls corner roundness of rectangles. In 0.14 all the tool options are being moved to the inspector and given labels, looks like this now:
![screen shot 2018-02-19 at 11 28 20 am](https://user-images.githubusercontent.com/4970417/36387839-087791fa-1568-11e8-99eb-236146f0d877.png)
