### ISSUE TITLE
We need a better tools for Ease for motion

### ISSUE THREAD

**Issue by rmros** [zrispo/wick-editor#784]
we need Ease-in Ease-out Ease-Custom and .... Tools , yea?
also its better we have auto continue key frame
meaning in layer i select one key frame for source and 30S later i choose  key frame for destination
i move object from stage 
and then other keyframe between source and destination will created!
maybe there is option in wick editor
but i didnt 
thanks for made this wonderfull

**Comment by zrispo** [comment]
Wick actually does have automatic creation of keyframes, I think it's broken right now (but I'll fix it ASAP)

**Comment by rmros** [comment]
@zrispo thankx
why animation is not smoothly?

**Comment by zrispo** [comment]
Fixed in 14.1!
