### ISSUE TITLE
HTML projects will render objects outside of the canvas

### ISSUE THREAD

**Issue by Luxapodular** [zrispo/wick-editor#787]

**Comment by Luxapodular** [comment]
It seems that this is only the case for objects with Positive x and y values. The renderer also causes the background color to extend. It looks like projects are filling the entire window, but the actual objects on screen are remaining regularly sized and in place.

**Comment by rmros** [comment]
Yes i saw that bug,
Why developer team didnt use tools like node es6 babel?
For example for decrease these bugs , we can use Tdd approach via mocha and other testing tools

**Comment by bbblitz** [comment]
@rmros Dependency on Node or any particular backend doesn't belong in a project like this! It would just make it harder to run for some people!

**Comment by rmros** [comment]
understand , your code be clean :)

**Comment by rmros** [comment]
thankyou reply me , got it
