### ISSUE TITLE
GotoAndStop() on Clip has a noticeable delay

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick-editor#810]
I have a simple Clip with 6 frames and this code attached to it:
this.gotoAndStop(6);

When I run the file, there is a short period during which the clip shows Frame 1. After a fraction of a second, it jumps to Frame 6 as intended. I tested this with parameters 2 through 5 and got the same result.

**Project File:**  (.WICK v0.14.1)
[GotoAndStop Lag-3.19.2018 3.08.05 PM.zip](https://github.com/zrispo/wick-editor/files/1826562/GotoAndStop.Lag-3.19.2018.3.08.05.PM.zip)

Chrome 65 / Windows 10 1709 x64

**Comment by zrispo** [comment]
Looks like `gotoAndStop` doesn't actually move the timeline of clips until one update later... weird, looking into this now
