### ISSUE TITLE
Rarely, images are positioned incorrectly when project is first loaded

### ISSUE THREAD

**Issue by zrispo** [zrispo/wick-editor#818]
Not sure what causes this, still looking into it

**Comment by Luxapodular** [comment]
This project has this issue every time it's loaded. It also occurs sometimes when leaving a clip and going back to the Root project. (The bone is a clip) 
[dragDropProject-3.22.2018 11.49.14 AM.wick.zip](https://github.com/zrispo/wick-editor/files/1838393/dragDropProject-3.22.2018.11.49.14.AM.wick.zip)
